package crypto

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
)

// Cert source values recorded alongside stored certificates.
const (
	// SourceSelfSigned marks a certificate generated by the gateway itself.
	SourceSelfSigned = "self-signed"
	// SourceCAIssued marks a certificate issued by an external CA for the KMS public key.
	SourceCAIssued = "ca-issued"
)

// GenerateCSR creates a PEM-encoded PKCS#10 certificate signing request for the
// given signer's public key. The request is signed by the KMS-backed signer, so
// the resulting certificate (issued by an external CA) will be usable with the
// private key that never leaves KMS.
//
// The CSR uses CN=entityID and SHA-256 with RSA, matching the KMS signing
// algorithm (RSASSA_PKCS1_V1_5_SHA_256).
func GenerateCSR(signer *KMSSigner, entityID string) ([]byte, error) {
	if signer == nil {
		return nil, fmt.Errorf("signer is nil")
	}
	if signer.Public() == nil {
		return nil, fmt.Errorf("signer public key unavailable")
	}

	template := &x509.CertificateRequest{
		Subject:            pkix.Name{CommonName: entityID},
		SignatureAlgorithm: x509.SHA256WithRSA,
	}

	der, err := x509.CreateCertificateRequest(rand.Reader, template, signer)
	if err != nil {
		return nil, fmt.Errorf("failed to create certificate request: %w", err)
	}

	return pem.EncodeToMemory(&pem.Block{
		Type:  "CERTIFICATE REQUEST",
		Bytes: der,
	}), nil
}

// ParseCertChainPEM parses one or more concatenated PEM CERTIFICATE blocks,
// returning the certificates in file order (leaf first by convention). Non-
// certificate PEM blocks are ignored.
func ParseCertChainPEM(data []byte) ([]*x509.Certificate, error) {
	var certs []*x509.Certificate
	rest := data
	for {
		var block *pem.Block
		block, rest = pem.Decode(rest)
		if block == nil {
			break
		}
		if block.Type != "CERTIFICATE" {
			continue
		}
		cert, err := x509.ParseCertificate(block.Bytes)
		if err != nil {
			return nil, fmt.Errorf("failed to parse certificate: %w", err)
		}
		certs = append(certs, cert)
	}
	if len(certs) == 0 {
		return nil, fmt.Errorf("no CERTIFICATE PEM block found")
	}
	return certs, nil
}

// PublicKeyMatchesSigner reports whether the certificate's public key is the
// same RSA key as the signer's (KMS) public key. This is the gate for importing
// an externally-issued certificate: the leaf must wrap the KMS public key so the
// KMS-held private key can produce signatures that validate against it.
func PublicKeyMatchesSigner(cert *x509.Certificate, signer *KMSSigner) (bool, error) {
	if cert == nil {
		return false, fmt.Errorf("certificate is nil")
	}
	if signer == nil {
		return false, fmt.Errorf("signer is nil")
	}

	certPub, ok := cert.PublicKey.(*rsa.PublicKey)
	if !ok {
		return false, fmt.Errorf("certificate public key is not RSA")
	}

	signerPub, ok := signer.Public().(*rsa.PublicKey)
	if !ok || signerPub == nil {
		return false, fmt.Errorf("signer public key is not RSA")
	}

	return certPub.N.Cmp(signerPub.N) == 0 && certPub.E == signerPub.E, nil
}
