# Identity Gateway cross-account resources for tenant acme
# Generated by the Identity Gateway onboarding wizard.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

variable "external_id" {
  description = "Identity Gateway-generated shared secret (from the onboarding wizard). Treated as opaque."
  type        = string
  sensitive   = true
  validation {
    condition     = can(regex("^[A-Z2-7]+$", var.external_id)) && length(var.external_id) >= 32 && length(var.external_id) <= 64
    error_message = "external_id must be base32 uppercase, 32-64 chars."
  }
}

variable "user_pool_id" {
  description = "The tenant Cognito user pool id (e.g. eu-north-1_AbC123xyz). Scopes the cognito-idp permissions to this pool — never widen to \"*\"."
  type        = string
  validation {
    condition     = can(regex("^[\\w-]+_[0-9a-zA-Z]+$", var.user_pool_id))
    error_message = "user_pool_id must look like <region>_<id>, e.g. eu-north-1_AbC123xyz."
  }
}

resource "aws_kms_key" "gateway" {
  description         = "Encrypts the Cognito client secret used by Identity Gateway (tenant acme)"
  enable_key_rotation = true
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AllowAccountRoot"
        Effect    = "Allow"
        Principal = { AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root" }
        Action    = "kms:*"
        Resource  = "*"
      },
      {
        Sid       = "AllowGatewayRole"
        Effect    = "Allow"
        Principal = { AWS = aws_iam_role.gateway.arn }
        Action    = ["kms:Decrypt", "kms:DescribeKey", "kms:GenerateDataKey"]
        Resource  = "*"
        Condition = {
          StringEquals = {
            "kms:ViaService" = "secretsmanager.${data.aws_region.current.name}.amazonaws.com"
          }
        }
      },
    ]
  })
}

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

locals {
  # Least-privilege: cognito-idp permissions are scoped to this tenant's user
  # pool ARN, never "*".
  cognito_pool_arn = "arn:aws:cognito-idp:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:userpool/${var.user_pool_id}"
}

resource "aws_secretsmanager_secret" "gateway" {
  name        = "identity-gateway-${data.aws_region.current.name}-acme-cognito-secret"
  description = "Cognito app client secret consumed by Identity Gateway"
  kms_key_id  = aws_kms_key.gateway.arn

  tags = {
    IdentityGatewayTenant = "acme"
  }
}

resource "aws_iam_role" "gateway" {
  name = "identity-gateway-acme"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::111122223333:role/identity-gateway-management-api" }
      Action    = "sts:AssumeRole"
      Condition = { StringEquals = { "sts:ExternalId" = var.external_id } }
    }]
  })

  tags = {
    IdentityGatewayTenant = "acme"
  }
}

resource "aws_iam_role_policy" "core" {
  name = "identity-gateway-core"
  role = aws_iam_role.gateway.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = [
          "cognito-idp:DescribeUserPool",
          "cognito-idp:DescribeUserPoolClient",
          "cognito-idp:DescribeUserPoolDomain",
          "cognito-idp:ListIdentityProviders",
        ]
        Resource = local.cognito_pool_arn
      },
      {
        Effect   = "Allow"
        Action   = "secretsmanager:GetSecretValue"
        Resource = aws_secretsmanager_secret.gateway.arn
      },
      {
        Effect   = "Allow"
        Action   = ["kms:Decrypt", "kms:DescribeKey", "kms:GenerateDataKey"]
        Resource = aws_kms_key.gateway.arn
      },
      {
        Effect   = "Allow"
        Action   = "iam:SimulatePrincipalPolicy"
        Resource = aws_iam_role.gateway.arn
      },
    ]
  })
}

resource "aws_iam_role_policy" "user_directory" {
  name = "identity-gateway-user-directory"
  role = aws_iam_role.gateway.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = [
        "cognito-idp:ListUsers",
        "cognito-idp:AdminGetUser",
        "cognito-idp:ListGroups",
        "cognito-idp:ListUsersInGroup",
        "cognito-idp:AdminListGroupsForUser",
      ]
      Resource = local.cognito_pool_arn
    }]
  })
}



output "role_arn" {
  description = "Paste this into the onboarding wizard (Step 4)"
  value       = aws_iam_role.gateway.arn
}

output "secret_arn" {
  description = "Paste this into the onboarding wizard (Step 4)"
  value       = aws_secretsmanager_secret.gateway.arn
}

output "kms_key_arn" {
  description = "KMS CMK encrypting the Cognito client secret"
  value       = aws_kms_key.gateway.arn
}
