import type { HelpContent } from '../contexts/HelpPanelContext';

// Contextual help for the Certificates page. Reflects the KMS-backed, pin-the-leaf
// signing model with active + optional backup certs and external-CA import.

const tableStyle: React.CSSProperties = { width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem', marginTop: '0.5rem' };
const cell: React.CSSProperties = { border: '1px solid #d1d5db', padding: '6px 8px', textAlign: 'left', verticalAlign: 'top' };

export const certificatesPageHelp: HelpContent = {
  header: <h2>Certificates</h2>,
  content: (
    <div>
      <p>
        The gateway signs SAML assertions and OIDC tokens with a single IdP <strong>signing
        certificate</strong>. The private key is generated in and never leaves AWS KMS — only the
        public certificate is stored (in DynamoDB) and published in metadata. The model is
        <strong> pin-the-leaf</strong>: relying parties trust the leaf certificate from your metadata.
      </p>
      <h3>What you can do</h3>
      <ul>
        <li><strong>Download</strong> the active certificate to hand to a relying party.</li>
        <li><strong>Generate CSR</strong> → have a corporate CA sign it → <strong>Import signed certificate</strong> (the key stays in KMS).</li>
        <li>Keep a <strong>backup</strong> certificate (on a second KMS key) ready to <strong>promote</strong> for an instant rollover.</li>
      </ul>
      <h3>Source</h3>
      <p>
        <strong>self-signed</strong> (generated by the gateway) or <strong>ca-issued</strong>
        (imported after a CA signed your CSR). When the active cert is CA-issued, automatic
        rotation backs off and signals <code>import_required</code> rather than self-signing over it.
      </p>
    </div>
  ),
};

export const activeCertHelp: HelpContent = {
  header: <h2>Active signing certificate</h2>,
  content: (
    <div>
      <p>The certificate currently used to sign all assertions and tokens.</p>
      <h3>Fields</h3>
      <dl>
        <dt><strong>Subject / Issuer</strong></dt>
        <dd>For self-signed certs these match (the gateway is its own issuer); for CA-issued, the issuer is your CA.</dd>
        <dt><strong>Signing key</strong></dt>
        <dd>Which KMS key backs this certificate (Primary or Backup).</dd>
        <dt><strong>Fingerprint</strong></dt>
        <dd>SHA-256 hash relying parties can pin. This is the value shown on each app's Integration tab.</dd>
        <dt><strong>Expiry / Days remaining</strong></dt>
        <dd>Validity window. An alarm fires when the active cert is close to expiry.</dd>
      </dl>
      <h3>External CA import</h3>
      <p>
        <strong>Generate CSR</strong> creates a certificate signing request for the KMS key's
        public key. Have your CA sign it, then <strong>Import signed certificate</strong>. The
        import is rejected unless the leaf's public key matches the KMS key (pin-the-leaf), so
        the private key never leaves KMS.
      </p>
    </div>
  ),
};

export const backupCertHelp: HelpContent = {
  header: <h2>Backup signing certificate</h2>,
  content: (
    <div>
      <p>
        A standby certificate, published in SAML metadata alongside the active one so relying
        parties already trust it <em>before</em> a rollover. <strong>Promote to active</strong>
        swaps it in instantly — useful for expiry or a key roll.
      </p>
      <h3>Backup key</h3>
      <p>
        When a separate backup KMS key is configured (<code>PROXY_KMS_KEY_ID_BACKUP</code>),
        promoting the backup is a genuine <em>key roll</em>. Without one, the backup uses the
        primary key (certificate renewal only). The OIDC JWKS publishes both keys during the
        grace window so in-flight tokens keep validating.
      </p>
      <h3>Typical use</h3>
      <ol>
        <li>Generate a CSR for the backup key and have your CA sign it.</li>
        <li>Import the signed cert here as the backup.</li>
        <li>When the active cert nears expiry, <strong>Promote</strong> — no metadata redistribution needed.</li>
      </ol>
    </div>
  ),
};

export const allCertsHelp: HelpContent = {
  header: <h2>All certificates</h2>,
  content: (
    <div>
      <p>Every certificate the gateway knows about, across roles.</p>
      <table style={tableStyle}>
        <thead><tr><th style={cell}>Role</th><th style={cell}>Meaning</th></tr></thead>
        <tbody>
          <tr><td style={cell}>active</td><td style={cell}>Currently used to sign.</td></tr>
          <tr><td style={cell}>backup</td><td style={cell}>Standby; published in metadata; can be promoted.</td></tr>
          <tr><td style={cell}>next</td><td style={cell}>Staged by automatic rotation (Plan 3 lifecycle).</td></tr>
        </tbody>
      </table>
      <p style={{ marginTop: '0.75rem' }}>
        Use the download action to export any certificate's public PEM. Private keys are never
        downloadable — they live only in KMS.
      </p>
    </div>
  ),
};
